-- AUTHORS data: restricted to mainstream authors (>= 30 books)
-- bio, photo_url = NULL
INSERT INTO authors (author_id, name, bio, photo_url) VALUES
(10, 'রবীন্দ্রনাথ ঠাকুর', NULL, NULL),
(62, 'বিভূতিভূষণ বন্দ্যোপাধ্যায়', NULL, NULL),
(230, 'রকিব হাসান', NULL, NULL),
(1, 'হুমায়ূন আহমেদ', NULL, NULL),
(126, 'মানিক বন্দ্যোপাধ্যায়', NULL, NULL),
(106, 'বঙ্কিমচন্দ্র চট্টোপাধ্যায়', NULL, NULL),
(85, 'সেলিনা হোসেন', NULL, NULL),
(31, 'আনিসুল হক', NULL, NULL),
(48, 'সৈয়দ শামসুল হক', NULL, NULL),
(59, 'শীর্ষেন্দু মুখোপাধ্যায়', NULL, NULL),
(9, 'সত্যজিৎ রায়', NULL, NULL),
(58, 'কাজী নজরুল ইসলাম', NULL, NULL),
(11, 'William Shakespeare', NULL, NULL),
(184, 'Stephen King', NULL, NULL),
(304, 'কাজী আনোয়ার হোসেন', NULL, NULL),
(243, 'উইলিয়াম শেক্সপীয়ার', NULL, NULL),
(225, 'সুমন্ত আসলাম', NULL, NULL),
(501, 'Agatha Christie', NULL, NULL),
(113, 'হেমেন্দ্রকুমার রায়', NULL, NULL),
(24, 'Rabindranath Tagore', NULL, NULL),
(441, 'পাওলো কোয়েলহো', NULL, NULL),
(181, 'J. K. Rowling', NULL, NULL),
(167, 'শওকত ওসমান', NULL, NULL),
(311, 'শামসুদ্দীন নওয়াব', NULL, NULL),
(328, 'আগাথা ক্রিস্টি', NULL, NULL),
(461, 'স্টিফেন হকিং', NULL, NULL),
(77, 'জহির রায়হান', NULL, NULL),
(289, 'ড্যান ব্রাউন', NULL, NULL),
(363, 'স্টিফেন কিং', NULL, NULL),
(6, 'সাদাত হোসাইন', NULL, NULL),
(176, 'Satyajit Ray', NULL, NULL),
(221, 'Paulo Coelho', NULL, NULL),
(78, 'শরৎচন্দ্র চট্টোপাধ্যায়', NULL, NULL),
(290, 'Dan Brown', NULL, NULL),
(2, 'ড. মিজানুর রহমান আজহারি', NULL, NULL),
(3, 'সালমা চৌধুরী', NULL, NULL),
(4, 'সবুজ আহম্মদ মুরসালিন', NULL, NULL),
(5, 'নুরুজ্জামান কাফি', NULL, NULL),
(7, 'ড. ফ. র. আল সিদ্দিক', NULL, NULL),
(8, 'মাহমুদ বিন নূর', NULL, NULL),
(593, 'R L Madan', NULL, NULL),
(909, 'S. Ranganatham', NULL, NULL);

SELECT setval(pg_get_serial_sequence('authors','author_id'), 909);

SELECT * FROM authors